---
name: colcon pytest
description: Continuous integration for colcon repositories
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo ::group::Initialize environment
        VENV=$(mktemp -d)
        python -m venv $VENV
        if [ -f $VENV/Scripts/activate ]; then
          . $VENV/Scripts/activate
        else
          . $VENV/bin/activate
        fi
        python -m pip install -U pip setuptools
        echo ::endgroup::

        echo ::group::Install dependencies
        # Install dependencies, including any 'test' extras, as well as pytest-cov
        python -m pip install -U -e .[test] pytest-cov -c ${{github.action_path}}/constraints.txt
        echo ::endgroup::

        echo ::group::Run tests
        python -m pytest --cov --cov-branch --cov-report xml:coverage.xml --cov-config setup.cfg
        echo ::endgroup::
