---
name: Run tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  canary:
    uses: ./.github/workflows/pytest.yaml
    with:
      codecov: false
      # Choose colcon-notification for a canary build. It has colcon
      # dependencies and debian patches, so exercieses a fair amount of the
      # CI action features.
      repository: colcon/colcon-notification
      # Use HEAD to find strategy.json file instead of the tip of colcon/ci
      setup-repository: ''
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yamllint -f github .
