name: Run tests

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  canary:
    uses: ./.github/workflows/pytest.yaml
    with:
      # Choose colcon-notification for a canary build. It has colcon
      # dependencies and debian patches, so exercieses a fair amount of the
      # CI action features.
      repository: colcon/colcon-notification
